/**
 * Agent Insights Panel
 * Shows all insights generated by agents across the investigation
 */

import { useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Lightbulb, ArrowUpRight } from 'lucide-react';
import { Card, CardHeader, CardTitle, Badge } from '@/components/ui';
import { agentProfiles, agentColorMap } from '@/agents';
import { useAgentOrchestrationStore } from '@/agents';
import type { AgentInsight } from '@/agents/types';

const severityBadge: Record<string, 'danger' | 'warning' | 'secondary' | 'default'> = {
  critical: 'danger',
  high: 'warning',
  medium: 'secondary',
  low: 'default',
  info: 'default',
};

export function AgentInsightsPanel() {
  const { completedTasks } = useAgentOrchestrationStore();

  const insights = useMemo(() => {
    const all: AgentInsight[] = [];
    for (const task of completedTasks) {
      if (task.result?.insights) {
        all.push(...task.result.insights);
      }
    }
    return all.sort((a, b) => b.confidence - a.confidence).slice(0, 16);
  }, [completedTasks]);

  return (
    <Card noPadding>
      <div className="p-5">
        <CardHeader>
          <CardTitle>
            <Lightbulb className="h-5 w-5 text-amber-400" />
            Agent Insights
          </CardTitle>
          <Badge variant="warning" size="sm">{insights.length} generated</Badge>
        </CardHeader>
      </div>

      <div className="max-h-[480px] overflow-y-auto px-5 pb-5">
        <AnimatePresence initial={false}>
          {insights.length === 0 ? (
            <div className="rounded-xl border border-slate-700/40 bg-slate-900/40 p-8 text-center text-sm text-gray-500">
              Insights will appear as agents complete their analysis.
            </div>
          ) : (
            <div className="space-y-2">
              {insights.map((insight, idx) => {
                const agent = agentProfiles.find((a) => a.id === insight.agentId);
                const color = agentColorMap[insight.agentRole] ?? '#6b7280';

                return (
                  <motion.div
                    key={insight.id}
                    initial={{ opacity: 0, x: 12 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: Math.min(idx * 0.04, 0.5), duration: 0.3 }}
                    className="rounded-lg border border-slate-700/40 bg-slate-950/40 p-3 hover:border-slate-600/60 transition-colors"
                  >
                    <div className="flex items-start gap-2 mb-2">
                      <span className="text-sm">{agent?.icon ?? '🤖'}</span>
                      <div className="flex-1 min-w-0">
                        <p className="text-[12px] font-medium text-white truncate">{insight.title}</p>
                        <p className="text-[11px] text-gray-400 mt-0.5">{insight.summary}</p>
                      </div>
                      <Badge variant={severityBadge[insight.severity] ?? 'default'} size="sm" className="text-[9px]">
                        {insight.severity}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-3 text-[10px] text-gray-500">
                      <span className="flex items-center gap-1">
                        <ArrowUpRight className="h-3 w-3" style={{ color }} />
                        {insight.type.replace(/_/g, ' ')}
                      </span>
                      <span>confidence: {insight.confidence.toFixed(0)}%</span>
                      <span>{insight.supportingEvidence.length} evidence items</span>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          )}
        </AnimatePresence>
      </div>
    </Card>
  );
}
